
services:
  backend:
    build: backend
    image: e2e-automl-backend:latest     
    ports:
      - "8000:8000"
      - "54321:54321"
    environment:
      - MLFLOW_TRACKING_URI=file:/app/backend/mlruns
      - MLFLOW_BACKEND_STORE_URI=/app/backend/mlruns
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/app/backend/mlruns
    volumes:
      - ./backend:/app/backend
    networks:
      - project_network

  frontend:
    build: frontend
    image: e2e-automl-frontend:latest
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on: 
      - backend
    networks:
      - project_network

  mlflow-ui:
    image: python:3.9
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=file:/app/backend/mlruns
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/app/backend/mlruns
    volumes:
      - ./backend:/app/backend
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir mlflow &&
             mlflow ui --backend-store-uri file:/app/backend/mlruns \
             --default-artifact-root /app/backend/mlruns \
             --host 0.0.0.0 --port 5000"
    networks:
      - project_network
  
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    environment:
      - ADMIN_PASSWORD=123456789Abcd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - project_network

volumes:
  portainer_data:
  

networks:
  project_network:
