name: CI-CD Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      # 1) Récupérer le code du dépôt
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2) Vérifier la présence de Docker
      - name: Debug – afficher le PATH
        run: |
          echo "PATH = $PATH"
          which docker || echo "docker non trouvé dans le PATH"

      # 3) Se connecter à Docker Hub
      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      # 4) Générer le TAG à partir du SHA de commit
      - name: Définir le tag d’image
        id: vars
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      # 5) Construire et pousser l’image Backend
      - name: Build & Push image backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DH_USERNAME }}/tp-final-a57-backend:${{ steps.vars.outputs.TAG }}

      # 6) Construire et pousser l’image Frontend
      - name: Build & Push image frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DH_USERNAME }}/tp-final-a57-frontend:${{ steps.vars.outputs.TAG }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      # 7) Refaire le checkout pour récupérer le docker-compose.yml
      - name: Checkout du code
        uses: actions/checkout@v4

      # 8) Déployer avec Docker Compose
      - name: Déploiement local avec docker compose
        run: |
          # Se placer dans le répertoire racine du dépôt cloné
          cd "${{ github.workspace }}"

          # Variables pour le docker-compose.yml
          export DH_USERNAME=${{ secrets.DH_USERNAME }}
          export TAG=${{ steps.vars.outputs.TAG }}

          # Pull des images depuis Docker Hub
          docker compose pull

          # Relancer les services en arrière-plan
          docker compose up -d

  notify:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      # 9) Envoyer une notification par e-mail
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.bell.net
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ✅ CI/CD terminé avec succès
          to: 2446546@bdeb.qc.ca
          from: GitHub Actions <2446546@bdeb.qc.ca>
          body: |
            Le workflow CI/CD dans le dépôt tp-final-a57 s'est exécuté avec succès !
